import { prisma } from '../src/lib/db'

const glossaryTerms = [
  // ==== COMP DESIGN ====
  { term: 'Accelerator', definition: 'A payout multiplier that increases when performance exceeds a threshold. Commonly misunderstood as a revenue driver - actually a timing device that shapes when deals close, not which deals close.', category: 'Comp Design', aliases: ['Kicker', 'Multiplier', 'Uplift'], relatedTerms: ['Quota', 'Payout Curve', 'Attainment'], examples: '100% accelerator at 100% quota means earning 2x on revenue beyond quota.' },
  { term: 'Quota', definition: 'The performance target used to calculate comp payout. Not the same as a forecast, a goal, or capacity. Quota is the number that determines what you earn.', category: 'Comp Design', aliases: ['Target'], relatedTerms: ['Attainment', 'Accelerator', 'Territory'], examples: 'Annual quota of $1M ARR for an Enterprise AE. Hit $1M = 100% attainment.' },
  { term: 'Attainment', definition: 'Performance as a percentage of quota. The number that determines where you land on the payout curve. 100% attainment = hit quota exactly.', category: 'Comp Design', aliases: ['Quota Attainment', 'Performance %'], relatedTerms: ['Quota', 'Payout Curve', 'Accelerator'], examples: 'Closed $850K against $1M quota = 85% attainment.' },
  { term: 'Payout Curve', definition: 'The function that maps attainment to comp payout. Defines thresholds, accelerators, caps, and the behavior incentives built into your plan.', category: 'Comp Design', aliases: ['Comp Curve', 'Commission Structure'], relatedTerms: ['Accelerator', 'Attainment', 'Quota'], examples: '0-70%: $0, 70-100%: 1x, 100-150%: 2x, 150%+: capped at 2x.' },
  { term: 'Threshold', definition: 'The attainment level where payout rules change. Below threshold = no payout or reduced rate. At/above threshold = full payout or accelerator kicks in.', category: 'Comp Design', aliases: ['Floor', 'Gate'], relatedTerms: ['Payout Curve', 'Accelerator'], examples: '70% threshold means no payout until 70% quota attainment.' },
  { term: 'Cap', definition: 'The maximum payout amount regardless of performance. Prevents runaway comp costs. Also demotivates top performers.', category: 'Comp Design', aliases: ['Ceiling', 'Max Payout'], relatedTerms: ['Payout Curve', 'Accelerator'], examples: 'Cap at 200% attainment = no additional comp beyond 2x quota performance.' },
  { term: 'OTE', definition: 'On-Target Earnings. Base salary plus variable comp at 100% quota attainment. The number recruiters use. Not what most reps actually earn.', category: 'Comp Design', aliases: ['Target Earnings', 'Plan Pay'], relatedTerms: ['Base Salary', 'Variable', 'Quota'], examples: '$80K base + $80K variable at quota = $160K OTE.' },
  { term: 'Variable', definition: 'The portion of comp tied to performance. Commission, bonus, incentive—whatever you call it, it\'s the money that varies based on results.', category: 'Comp Design', aliases: ['Commission', 'Incentive', 'Bonus'], relatedTerms: ['OTE', 'Base Salary', 'Payout Curve'], examples: 'OTE $160K with 50/50 split = $80K base, $80K variable at quota.' },
  { term: 'MBO', definition: 'Management By Objectives. Subjective goals in comp plans. Often used when objective measures are hard. Always controversial at payout time.', category: 'Comp Design', aliases: ['Objectives', 'Discretionary Bonus'], relatedTerms: ['Quota', 'Measure'], examples: '20% of variable tied to "customer satisfaction" or "team leadership" - manager decides payout.' },
  { term: 'SPIF', definition: 'Sales Performance Incentive Fund. Short-term contest or bonus for specific behavior. Drives the behavior you incent, often at expense of other metrics.', category: 'Comp Design', aliases: ['Contest', 'Accelerator Program'], relatedTerms: ['Quota', 'Measure'], examples: 'Close 3 deals in Q4, earn $5K bonus. Reps push small deals to hit count, ignore large strategic deals.' },
  { term: 'Pay Mix', definition: 'The ratio of base salary to variable compensation. 50/50 is common for field sales. 80/20 for account managers. Higher variable = more risk, more upside.', category: 'Comp Design', aliases: ['Comp Mix', 'Salary Split'], relatedTerms: ['OTE', 'Variable', 'Base Salary'], examples: 'Enterprise AE with $200K OTE at 50/50 = $100K base + $100K variable.' },
  { term: 'Base Salary', definition: 'Fixed compensation regardless of performance. The guaranteed portion of total comp. Not earned through sales—paid for showing up.', category: 'Comp Design', aliases: ['Fixed Pay', 'Guaranteed'], relatedTerms: ['OTE', 'Variable', 'Pay Mix'], examples: '$100K base in a $200K OTE package at 50/50 mix.' },
  { term: 'Rate Table', definition: 'The lookup table that defines commission rates at different attainment levels. The math behind the payout curve in tabular form.', category: 'Comp Design', aliases: ['Commission Table', 'Rate Card'], relatedTerms: ['Payout Curve', 'Attainment', 'Threshold'], examples: '0-70%: 0.5x, 71-100%: 1.0x, 101-150%: 1.5x, 151%+: 2.0x.' },
  { term: 'Decelerator', definition: 'A payout multiplier that decreases below a threshold. Below quota = earn less per dollar. The stick to the accelerator\'s carrot.', category: 'Comp Design', aliases: ['Penalty Rate', 'Reduced Rate'], relatedTerms: ['Accelerator', 'Threshold', 'Payout Curve'], examples: 'Below 70% quota: 0.5x rate. Closing $50K counts as $25K toward earnings.' },
  { term: 'Guarantee', definition: 'Minimum payout regardless of performance. Common for new hires during ramp. Also called protected earnings or floor.', category: 'Comp Design', aliases: ['Floor', 'Protected Earnings', 'Ramp Guarantee'], relatedTerms: ['Draw', 'OTE', 'Ramp Period'], examples: 'First 6 months: guaranteed 80% of OTE regardless of performance.' },
  { term: 'Ramp Period', definition: 'Time given to new reps to reach full productivity. Usually 3-6 months. Quota is often reduced during ramp.', category: 'Comp Design', aliases: ['Ramp', 'Onboarding Period'], relatedTerms: ['Guarantee', 'Quota', 'New Hire'], examples: 'Month 1: 50% quota, Month 2: 75% quota, Month 3+: 100% quota.' },
  { term: 'Windfall', definition: 'Unexpectedly large commission from a deal outside normal performance. Usually triggers cap or clawback policy reviews.', category: 'Comp Design', aliases: ['Bluebird', 'Lucky Deal'], relatedTerms: ['Cap', 'Override', 'Governance'], examples: 'Rep inherits $5M deal from terminated colleague. Pays out $500K commission. Finance panics.' },
  { term: 'Override', definition: 'Manual adjustment to calculated commission. Used for exceptions, errors, or special situations. Creates audit trail nightmares when overused.', category: 'Comp Design', aliases: ['Manual Adjustment', 'Exception'], relatedTerms: ['Governance', 'Audit', 'Admin'], examples: 'Rep should have gotten credit but system missed it. Override adds $5K to payout.' },
  { term: 'Linked Plan', definition: 'Comp plan where payout depends on another person\'s or team\'s performance. Manager plans often linked to team attainment.', category: 'Comp Design', aliases: ['Rollup Plan', 'Dependent Plan'], relatedTerms: ['Manager Comp', 'Team Attainment'], examples: 'Sales manager earns accelerator only if 80% of team hits quota.' },
  { term: 'Component', definition: 'A distinct measure or incentive within a comp plan. Plans can have multiple components weighted differently.', category: 'Comp Design', aliases: ['Plan Element', 'Incentive Component'], relatedTerms: ['Measure', 'Weighting', 'Plan Design'], examples: 'Plan has 3 components: New ARR (60%), Renewal ARR (30%), MBO (10%).' },
  { term: 'Weighting', definition: 'How much each component counts toward total variable. Higher weight = bigger impact on payout.', category: 'Comp Design', aliases: ['Component Weight', 'Allocation'], relatedTerms: ['Component', 'Variable', 'Pay Mix'], examples: 'New business 70%, expansion 20%, retention 10% of variable.' },
  { term: 'Period', definition: 'The timeframe for measuring performance and calculating payout. Monthly, quarterly, semi-annual, or annual.', category: 'Comp Design', aliases: ['Measurement Period', 'Comp Period'], relatedTerms: ['Quota', 'Attainment', 'Payout'], examples: 'Monthly commission on deals closed. Quarterly accelerator calculation.' },

  // ==== ADMIN / OPERATIONS ====
  { term: 'Split', definition: 'Credit allocation across multiple reps on the same deal. The math that prevents "who gets credit" wars. Also the cause of most SPM disputes when done wrong.', category: 'Admin', aliases: ['Credit Split', 'Deal Split', 'Overlay Credit'], relatedTerms: ['Overlay', 'Territory', 'Crediting Rules'], examples: 'AE gets 60%, SE gets 40% on a $100K deal. AE credited $60K, SE credited $40K.' },
  { term: 'Measure', definition: 'The metric used to calculate comp. Revenue, bookings, ARR, pipeline, activity—whatever you pay on. The source of truth for "what counts."', category: 'Admin', aliases: ['Metric', 'KPI', 'Performance Measure'], relatedTerms: ['Quota', 'Crediting', 'Data Source'], examples: 'New ARR (Annual Recurring Revenue) as primary measure for SaaS sales comp.' },
  { term: 'SPM System', definition: 'The software platform that calculates, tracks, and pays out sales compensation. Not your CRM. Not your ERP. The dedicated system for comp math.', category: 'Admin', aliases: ['Incentive Comp Platform', 'ICM System', 'Comp Platform'], relatedTerms: ['Vendor', 'Integration', 'Data Pipeline'], examples: 'Vendors: Xactly, CaptivateIQ, Spiff, Varicent, SAP, Anaplan.' },
  { term: 'Draw', definition: 'Advance payment against future commissions. Must be repaid from earnings. Creates debt for low performers.', category: 'Admin', aliases: ['Commission Draw', 'Advance'], relatedTerms: ['Clawback', 'Recovery'], examples: '$5K monthly draw. If you earn $4K in commissions, you owe $1K back.' },
  { term: 'Clawback', definition: 'Recovery of paid commissions when deals cancel or downgrade. The policy that creates disputes.', category: 'Admin', aliases: ['Chargeback', 'Recovery'], relatedTerms: ['Draw', 'Deal Cancellation'], examples: 'Customer churns after 3 months. Rep pays back 50% of original commission.' },
  { term: 'Routing Rules', definition: 'Automated logic that assigns leads/opportunities to reps. Works great until edge cases break it.', category: 'Admin', aliases: ['Lead Assignment', 'Auto-Assignment'], relatedTerms: ['Territory', 'Coverage Model'], examples: 'Route inbound leads to rep who owns account territory. Breaks when account spans multiple territories or rep is on leave.' },
  { term: 'True-Up', definition: 'Adjustment payment to correct previous calculation errors. Usually happens at period end when data finally reconciles.', category: 'Admin', aliases: ['Reconciliation', 'Catch-Up'], relatedTerms: ['Period', 'Data Quality', 'Audit'], examples: 'Q4 true-up adds $8K when deal data finally synced from Salesforce.' },
  { term: 'Data Feed', definition: 'Automated flow of transaction data from source systems into SPM. CRM to comp. ERP to comp. The pipeline that makes or breaks calculation accuracy.', category: 'Admin', aliases: ['Integration', 'Data Pipeline'], relatedTerms: ['SPM System', 'Data Quality'], examples: 'Nightly feed from Salesforce opportunities to Xactly. Hourly feed from NetSuite for bookings.' },
  { term: 'Shadow Accounting', definition: 'Reps tracking their own commissions in spreadsheets because they don\'t trust the system. Sign of SPM failure.', category: 'Admin', aliases: ['Side Spreadsheet', 'Rep Tracking'], relatedTerms: ['Trust', 'Transparency', 'Dispute'], examples: 'Every rep has a personal Excel to verify their commission calculations.' },
  { term: 'Comp Statement', definition: 'The report showing a rep their earnings for a period. Should be clear and auditable. Usually isn\'t.', category: 'Admin', aliases: ['Pay Statement', 'Commission Statement'], relatedTerms: ['Transparency', 'Payout', 'Audit'], examples: 'Monthly statement showing: deals closed, credit amounts, rates applied, total payout.' },
  { term: 'Effective Date', definition: 'When a plan or rate change takes effect. Determines which rules apply to which deals.', category: 'Admin', aliases: ['Start Date', 'Go-Live Date'], relatedTerms: ['Plan Document', 'Amendment', 'Retroactive'], examples: 'New accelerator effective April 1. Deals closed March 31 use old rates.' },
  { term: 'Retroactive', definition: 'Applying changes to past transactions. Usually causes disputes. Sometimes necessary for corrections.', category: 'Admin', aliases: ['Backdated', 'Historical'], relatedTerms: ['True-Up', 'Effective Date', 'Amendment'], examples: 'Retroactive quota adjustment for territory change. Recalculates last 3 months.' },
  { term: 'Payment Hold', definition: 'Blocking commission payment pending investigation or verification. Used for disputed deals or policy violations.', category: 'Admin', aliases: ['Hold', 'Pending'], relatedTerms: ['Dispute', 'Governance', 'Payout'], examples: 'Payment held on $50K deal while verifying customer actually signed contract.' },

  // ==== GOVERNANCE ====
  { term: 'Territory', definition: 'The defined market segment a rep can sell into. Can be geographic, account-based, vertical-based, or product-based. The boundary that determines who gets credit for what.', category: 'Governance', aliases: ['Patch', 'Book of Business', 'Assigned Accounts'], relatedTerms: ['Split', 'Coverage Model', 'Routing Rules'], examples: 'West Coast Enterprise accounts with >$50M revenue in Financial Services vertical.' },
  { term: 'Overlay', definition: 'A sales role that covers multiple territories or accounts without owning them. Gets partial credit on deals. The cause of most territory disputes.', category: 'Governance', aliases: ['Solutions Engineer', 'Overlay Rep'], relatedTerms: ['Split', 'Territory', 'Coverage Model'], examples: 'SE overlays 50 enterprise accounts, gets 30-40% credit on deals they support.' },
  { term: 'Crediting', definition: 'The rules that determine which rep gets credit for which revenue. The source of 80% of SPM disputes.', category: 'Governance', aliases: ['Credit Rules', 'Attribution'], relatedTerms: ['Split', 'Territory', 'Routing'], examples: 'Deal credits to rep who owns the account at close date, regardless of who sourced it.' },
  { term: 'Coverage Model', definition: 'How you assign reps to market opportunity. Territory design, account ownership, overlay structure. The foundation that determines who can sell what.', category: 'Governance', aliases: ['Go-to-Market Model', 'Sales Structure'], relatedTerms: ['Territory', 'Overlay', 'Routing'], examples: 'Enterprise direct + channel + inside sales + solutions overlay = 4-layer coverage model.' },
  { term: 'Plan Document', definition: 'The legal document defining comp plan terms. Should be clear and complete. Usually has loopholes that create disputes.', category: 'Governance', aliases: ['Comp Plan', 'ICM Agreement'], relatedTerms: ['Amendment', 'Effective Date', 'Policy'], examples: '20-page document: definitions, rates, conditions, exceptions, signature lines.' },
  { term: 'Amendment', definition: 'Change to an existing plan document. Requires acknowledgment. Often causes confusion about which rules apply when.', category: 'Governance', aliases: ['Plan Change', 'Addendum'], relatedTerms: ['Plan Document', 'Effective Date'], examples: 'Mid-year amendment: "Effective July 1, accelerator threshold changes from 100% to 110%."' },
  { term: 'Policy', definition: 'Rules governing edge cases and exceptions in comp. Clawback policy, split policy, LOA policy. The decisions that precedent creates.', category: 'Governance', aliases: ['Rule', 'Guideline'], relatedTerms: ['Plan Document', 'Governance Committee'], examples: 'Split policy: Deals with >3 reps require VP approval. No splits below 20%.' },
  { term: 'Governance Committee', definition: 'Cross-functional team that makes comp decisions. Sales, Finance, HR, Legal. Should meet regularly. Usually only meets when there\'s a problem.', category: 'Governance', aliases: ['Comp Committee', 'ICM Council'], relatedTerms: ['Policy', 'Dispute Resolution'], examples: 'Monthly governance meeting: Sales VP, CFO, HR Director, Legal review exceptions and disputes.' },
  { term: 'Dispute', definition: 'Formal challenge to a comp calculation or crediting decision. The symptom of governance failure.', category: 'Governance', aliases: ['Exception Request', 'Challenge'], relatedTerms: ['Governance Committee', 'Policy', 'Resolution'], examples: 'Rep disputes credit: "I sourced this deal, I should get full credit not 60%."' },
  { term: 'Carve-Out', definition: 'Exclusion from standard plan rules. Special deals, strategic accounts, or unique circumstances.', category: 'Governance', aliases: ['Exception', 'Special Case'], relatedTerms: ['Policy', 'Override', 'Governance'], examples: 'Strategic account carve-out: CEO-sponsored deals paid at flat 5% regardless of plan.' },
  { term: 'Quota Relief', definition: 'Reduction to quota for factors outside rep control. Territory changes, product discontinuation, market events.', category: 'Governance', aliases: ['Quota Adjustment', 'Relief'], relatedTerms: ['Quota', 'Governance Committee'], examples: 'Rep gets 20% quota relief when major account moves to new rep\'s territory.' },

  // ==== IMPLEMENTATION & VENDORS ====
  { term: 'ICM', definition: 'Incentive Compensation Management. The formal name for SPM systems and processes. What consultants call it.', category: 'Implementation', aliases: ['Incentive Comp', 'SPM'], relatedTerms: ['SPM System', 'Vendor'], examples: 'Gartner Magic Quadrant for ICM. Forrester Wave ICM report.' },
  { term: 'ASC 606', definition: 'Accounting standard for revenue recognition. Impacts when commission costs are recognized. The reason Finance cares about SPM data.', category: 'Implementation', aliases: ['Revenue Recognition', 'Commission Amortization'], relatedTerms: ['Cost of Sale', 'Finance'], examples: 'ASC 606 requires amortizing commission cost over customer contract period.' },
  { term: 'Cost of Sale', definition: 'Commission as a percentage of revenue. The metric Finance watches. Higher isn\'t always worse—depends on deal quality.', category: 'Implementation', aliases: ['COS', 'Commission Rate'], relatedTerms: ['ASC 606', 'Finance', 'Budget'], examples: '12% cost of sale = $12K commission paid per $100K revenue.' },
  { term: 'Implementation Partner', definition: 'Consulting firm that deploys SPM systems. Some good, some terrible. Check references.', category: 'Implementation', aliases: ['SI', 'Systems Integrator', 'Partner'], relatedTerms: ['Vendor', 'SPM System'], examples: 'Big 4 for enterprise. Boutique firms for mid-market. Vendor PS teams vary widely.' },
  { term: 'Configuration', definition: 'Setting up SPM system rules without custom code. Preferred approach. Usually insufficient for complex plans.', category: 'Implementation', aliases: ['Setup', 'Admin Config'], relatedTerms: ['Customization', 'SPM System'], examples: 'Configure rate tables, thresholds, and plan assignments in admin UI.' },
  { term: 'Customization', definition: 'Custom code to extend SPM system capabilities. Sometimes necessary. Always creates technical debt and upgrade headaches.', category: 'Implementation', aliases: ['Development', 'Custom Code'], relatedTerms: ['Configuration', 'SPM System'], examples: 'Custom integration to legacy ERP. Custom calculation for complex split logic.' },
  { term: 'User Acceptance Testing', definition: 'Validating SPM system before go-live. Should involve actual reps and actual deals. Usually rushed.', category: 'Implementation', aliases: ['UAT', 'Testing'], relatedTerms: ['Go-Live', 'Parallel Run'], examples: 'Test 100 deals across all plan types. Verify each calculation matches expected result.' },
  { term: 'Parallel Run', definition: 'Running new and old systems simultaneously to verify accuracy. Essential for major changes. Often skipped.', category: 'Implementation', aliases: ['Parallel Processing'], relatedTerms: ['UAT', 'Go-Live', 'Migration'], examples: '3-month parallel run: calculate in both systems, compare results, resolve discrepancies.' },
  { term: 'Data Migration', definition: 'Moving historical comp data to new system. Harder than it sounds. Usually reveals data quality issues.', category: 'Implementation', aliases: ['Migration', 'Data Conversion'], relatedTerms: ['Go-Live', 'Parallel Run'], examples: 'Migrate 3 years of transaction history, plan documents, and payment records.' },

  // ==== ANALYTICS & REPORTING ====
  { term: 'Attainment Distribution', definition: 'How quota performance spreads across the sales team. Healthy is normal curve around 100%. Reality is usually bimodal.', category: 'Analytics', aliases: ['Performance Distribution', 'Quota Distribution'], relatedTerms: ['Attainment', 'Quota', 'Benchmark'], examples: 'Distribution shows: 20% below 70%, 50% at 80-120%, 30% above 120%. Quotas may be wrong.' },
  { term: 'Payout Ratio', definition: 'Actual comp paid versus target comp. Under 1.0 means underperformance or plan design issue.', category: 'Analytics', aliases: ['Pay/Target Ratio'], relatedTerms: ['OTE', 'Attainment', 'Cost of Sale'], examples: '0.85 payout ratio = team earned 85% of target comp. Need to investigate why.' },
  { term: 'Quota Coverage', definition: 'Total team quota versus revenue target. Should be 80-120% depending on model. Higher isn\'t always better.', category: 'Analytics', aliases: ['Coverage Ratio'], relatedTerms: ['Quota', 'Capacity Planning'], examples: '110% quota coverage = quotas sum to 10% more than revenue target. Allows for attrition.' },
  { term: 'Plan Effectiveness', definition: 'Whether the comp plan drives intended behavior. Measured by correlation between comp earned and business outcomes.', category: 'Analytics', aliases: ['Comp Effectiveness'], relatedTerms: ['Behavior', 'Design', 'Outcomes'], examples: 'High new logo bonus but reps still focus on expansion = plan not effective.' },
  { term: 'Churn Impact', definition: 'Effect of customer cancellations on comp and cost. Often ignored in plan design until it\'s too late.', category: 'Analytics', aliases: ['Cancellation Impact'], relatedTerms: ['Clawback', 'Retention'], examples: '20% customer churn, no clawback = paying commission on revenue that doesn\'t stick.' },
  { term: 'Comp Accrual', definition: 'Estimated commission liability for accounting purposes. Finance needs accurate accruals for financial statements.', category: 'Analytics', aliases: ['Commission Accrual', 'Liability'], relatedTerms: ['ASC 606', 'Finance'], examples: 'Monthly comp accrual based on pipeline and close rates. Trued up at period end.' },
  { term: 'Earnings Forecast', definition: 'Projected commission based on pipeline and historical performance. Helps reps and Finance plan.', category: 'Analytics', aliases: ['Comp Forecast'], relatedTerms: ['Pipeline', 'Attainment'], examples: 'Rep sees: "At current pace, you\'ll earn $95K this quarter. Close Deal X to hit $110K."' },
  { term: 'Benchmark', definition: 'Industry comparison data for comp practices. Pay levels, plan structures, attainment rates. Essential for competitive plans.', category: 'Analytics', aliases: ['Market Data', 'Comp Survey'], relatedTerms: ['OTE', 'Pay Mix', 'Design'], examples: 'Radford, Comptryx, Alexander Group surveys show median Enterprise AE OTE.' },
]

async function main() {
  console.log('Seeding glossary terms...')
  for (const term of glossaryTerms) {
    await prisma.glossaryTerm.upsert({
      where: { term: term.term },
      update: term,
      create: term,
    })
  }
  console.log(`✓ Seeded ${glossaryTerms.length} glossary terms`)
}

main().catch(console.error).finally(() => process.exit(0))
