import { prisma } from '../src/lib/db'

const glossaryTerms = [
  { term: 'Accelerator', definition: 'A payout multiplier that increases when performance exceeds a threshold. Commonly misunderstood as a revenue driver - actually a timing device that shapes when deals close, not which deals close.', category: 'Comp Design', aliases: ['Kicker', 'Multiplier', 'Uplift'], relatedTerms: ['Quota', 'Payout Curve', 'Attainment'], examples: '100% accelerator at 100% quota means earning 2x on revenue beyond quota.' },
  { term: 'Quota', definition: 'The performance target used to calculate comp payout. Not the same as a forecast, a goal, or capacity. Quota is the number that determines what you earn.', category: 'Comp Design', aliases: ['Target'], relatedTerms: ['Attainment', 'Accelerator', 'Territory'], examples: 'Annual quota of $1M ARR for an Enterprise AE. Hit $1M = 100% attainment.' },
  { term: 'Split', definition: 'Credit allocation across multiple reps on the same deal. The math that prevents "who gets credit" wars. Also the cause of most SPM disputes when done wrong.', category: 'Admin', aliases: ['Credit Split', 'Deal Split', 'Overlay Credit'], relatedTerms: ['Overlay', 'Territory', 'Crediting Rules'], examples: 'AE gets 60%, SE gets 40% on a $100K deal. AE credited $60K, SE credited $40K.' },
  { term: 'Territory', definition: 'The defined market segment a rep can sell into. Can be geographic, account-based, vertical-based, or product-based. The boundary that determines who gets credit for what.', category: 'Governance', aliases: ['Patch', 'Book of Business', 'Assigned Accounts'], relatedTerms: ['Split', 'Coverage Model', 'Routing Rules'], examples: 'West Coast Enterprise accounts with >$50M revenue in Financial Services vertical.' },
  { term: 'Attainment', definition: 'Performance as a percentage of quota. The number that determines where you land on the payout curve. 100% attainment = hit quota exactly.', category: 'Comp Design', aliases: ['Quota Attainment', 'Performance %'], relatedTerms: ['Quota', 'Payout Curve', 'Accelerator'], examples: 'Closed $850K against $1M quota = 85% attainment.' },
  { term: 'Payout Curve', definition: 'The function that maps attainment to comp payout. Defines thresholds, accelerators, caps, and the behavior incentives built into your plan.', category: 'Comp Design', aliases: ['Comp Curve', 'Commission Structure'], relatedTerms: ['Accelerator', 'Attainment', 'Quota'], examples: '0-70%: $0, 70-100%: 1x, 100-150%: 2x, 150%+: capped at 2x.' },
  { term: 'Measure', definition: 'The metric used to calculate comp. Revenue, bookings, ARR, pipeline, activity—whatever you pay on. The source of truth for "what counts."', category: 'Admin', aliases: ['Metric', 'KPI', 'Performance Measure'], relatedTerms: ['Quota', 'Crediting', 'Data Source'], examples: 'New ARR (Annual Recurring Revenue) as primary measure for SaaS sales comp.' },
  { term: 'SPM System', definition: 'The software platform that calculates, tracks, and pays out sales compensation. Not your CRM. Not your ERP. The dedicated system for comp math.', category: 'Admin', aliases: ['Incentive Comp Platform', 'ICM System', 'Comp Platform'], relatedTerms: ['Vendor', 'Integration', 'Data Pipeline'], examples: 'Vendors: Xactly, CaptivateIQ, Spiff, Varicent, SAP, Anaplan.' },
  { term: 'Overlay', definition: 'A sales role that covers multiple territories or accounts without owning them. Gets partial credit on deals. The cause of most territory disputes.', category: 'Governance', aliases: ['Solutions Engineer', 'Overlay Rep'], relatedTerms: ['Split', 'Territory', 'Coverage Model'], examples: 'SE overlays 50 enterprise accounts, gets 30-40% credit on deals they support.' },
  { term: 'Threshold', definition: 'The attainment level where payout rules change. Below threshold = no payout or reduced rate. At/above threshold = full payout or accelerator kicks in.', category: 'Comp Design', aliases: ['Floor', 'Gate'], relatedTerms: ['Payout Curve', 'Accelerator'], examples: '70% threshold means no payout until 70% quota attainment.' },
  { term: 'Cap', definition: 'The maximum payout amount regardless of performance. Prevents runaway comp costs. Also demotivates top performers.', category: 'Comp Design', aliases: ['Ceiling', 'Max Payout'], relatedTerms: ['Payout Curve', 'Accelerator'], examples: 'Cap at 200% attainment = no additional comp beyond 2x quota performance.' },
  { term: 'Draw', definition: 'Advance payment against future commissions. Must be repaid from earnings. Creates debt for low performers.', category: 'Admin', aliases: ['Commission Draw', 'Advance'], relatedTerms: ['Clawback', 'Recovery'], examples: '$5K monthly draw. If you earn $4K in commissions, you owe $1K back.' },
  { term: 'Clawback', definition: 'Recovery of paid commissions when deals cancel or downgrade. The policy that creates disputes.', category: 'Admin', aliases: ['Chargeback', 'Recovery'], relatedTerms: ['Draw', 'Deal Cancellation'], examples: 'Customer churns after 3 months. Rep pays back 50% of original commission.' },
  { term: 'OTE', definition: 'On-Target Earnings. Base salary plus variable comp at 100% quota attainment. The number recruiters use. Not what most reps actually earn.', category: 'Comp Design', aliases: ['Target Earnings', 'Plan Pay'], relatedTerms: ['Base Salary', 'Variable', 'Quota'], examples: '$80K base + $80K variable at quota = $160K OTE.' },
  { term: 'Variable', definition: 'The portion of comp tied to performance. Commission, bonus, incentive—whatever you call it, it's the money that varies based on results.', category: 'Comp Design', aliases: ['Commission', 'Incentive', 'Bonus'], relatedTerms: ['OTE', 'Base Salary', 'Payout Curve'], examples: 'OTE $160K with 50/50 split = $80K base, $80K variable at quota.' },
  { term: 'Crediting', definition: 'The rules that determine which rep gets credit for which revenue. The source of 80% of SPM disputes.', category: 'Governance', aliases: ['Credit Rules', 'Attribution'], relatedTerms: ['Split', 'Territory', 'Routing'], examples: 'Deal credits to rep who owns the account at close date, regardless of who sourced it.' },
  { term: 'MBO', definition: 'Management By Objectives. Subjective goals in comp plans. Often used when objective measures are hard. Always controversial at payout time.', category: 'Comp Design', aliases: ['Objectives', 'Discretionary Bonus'], relatedTerms: ['Quota', 'Measure'], examples: '20% of variable tied to "customer satisfaction" or "team leadership" - manager decides payout.' },
  { term: 'SPIF', definition: 'Sales Performance Incentive Fund. Short-term contest or bonus for specific behavior. Drives the behavior you incent, often at expense of other metrics.', category: 'Comp Design', aliases: ['Contest', 'Accelerator Program'], relatedTerms: ['Quota', 'Measure'], examples: 'Close 3 deals in Q4, earn $5K bonus. Reps push small deals to hit count, ignore large strategic deals.' },
  { term: 'Coverage Model', definition: 'How you assign reps to market opportunity. Territory design, account ownership, overlay structure. The foundation that determines who can sell what.', category: 'Governance', aliases: ['Go-to-Market Model', 'Sales Structure'], relatedTerms: ['Territory', 'Overlay', 'Routing'], examples: 'Enterprise direct + channel + inside sales + solutions overlay = 4-layer coverage model.' },
  { term: 'Routing Rules', definition: 'Automated logic that assigns leads/opportunities to reps. Works great until edge cases break it.', category: 'Admin', aliases: ['Lead Assignment', 'Auto-Assignment'], relatedTerms: ['Territory', 'Coverage Model'], examples: 'Route inbound leads to rep who owns account territory. Breaks when account spans multiple territories or rep is on leave.' },
];

async function main() {
  console.log('Seeding glossary terms...')
  for (const term of glossaryTerms) {
    await prisma.glossaryTerm.upsert({
      where: { term: term.term },
      update: term,
      create: term,
    })
  }
  console.log(`✓ Seeded ${glossaryTerms.length} glossary terms`)
}

main().catch(console.error).finally(() => process.exit(0))
